lib/blog_web/router.ex
defmodule BlogWeb.Router do
  use BlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {BlogWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BlogWeb do
    pipe_through :browser

    get "/", PageController, :home
    get "/sobre", PageController, :about
    get "/posts", PageController, :index
    get "/posts/:id", PostController, :show
  end

  if Application.compile_env(:blog, :dev_routes) do
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: BlogWeb.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/blog/application.ex
defmodule Blog.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      BlogWeb.Telemetry,
      Blog.Repo,
      {DNSCluster, query: Application.get_env(:blog, :dns_cluster_query) || :ignore},
      {Phoenix.PubSub, name: Blog.PubSub},
      # Start the Finch HTTP client for sending emails
      {Finch, name: Blog.Finch},
      # Start a worker by calling: Blog.Worker.start_link(arg)
      # {Blog.Worker, arg},
      # Start to serve requests, typically the last entry
      BlogWeb.Endpoint
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Blog.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    BlogWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/blog/content.ex
defmodule Blog.Content do
  @moduledoc """
  The Content context.
  """

  import Ecto.Query, warn: false
  alias Blog.Repo

  alias Blog.Content.Post

  @doc """
  Returns the list of posts.

  ## Examples

      iex> list_posts()
      [%Post{}, ...]

  """
  def list_posts do
    Repo.all(Post)
  end

  @doc """
  Gets a single post.

  Raises `Ecto.NoResultsError` if the Post does not exist.

  ## Examples

      iex> get_post!(123)
      %Post{}

      iex> get_post!(456)
      ** (Ecto.NoResultsError)

  """
  def get_post!(id), do: Repo.get!(Post, id)

  @doc """
  Creates a post.

  ## Examples

      iex> create_post(%{field: value})
      {:ok, %Post{}}

      iex> create_post(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_post(attrs \\ %{}) do
    %Post{}
    |> Post.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a post.

  ## Examples

      iex> update_post(post, %{field: new_value})
      {:ok, %Post{}}

      iex> update_post(post, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_post(%Post{} = post, attrs) do
    post
    |> Post.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a post.

  ## Examples

      iex> delete_post(post)
      {:ok, %Post{}}

      iex> delete_post(post)
      {:error, %Ecto.Changeset{}}

  """
  def delete_post(%Post{} = post) do
    Repo.delete(post)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking post changes.

  ## Examples

      iex> change_post(post)
      %Ecto.Changeset{data: %Post{}}

  """
  def change_post(%Post{} = post, attrs \\ %{}) do
    Post.changeset(post, attrs)
  end
end

lib/blog/content/post.ex
defmodule Blog.Content.Post do
  use Ecto.Schema
  import Ecto.Changeset

  schema "posts" do
    field :title, :string
    field :body, :string

    timestamps(type: :utc_datetime)
  end

  @doc false
  def changeset(post, attrs) do
    post
    |> cast(attrs, [:title, :body])
    |> validate_required([:title, :body])
  end
end

lib/blog/mailer.ex
defmodule Blog.Mailer do
  use Swoosh.Mailer, otp_app: :blog
end

lib/blog/repo.ex
defmodule Blog.Repo do
  use Ecto.Repo,
    otp_app: :blog,
    adapter: Ecto.Adapters.Postgres
end

lib/blog_web/controllers/error_html.ex
defmodule BlogWeb.ErrorHTML do
  @moduledoc """
  This module is invoked by your endpoint in case of errors on HTML requests.

  See config/config.exs.
  """
  use BlogWeb, :html

  # If you want to customize your error pages,
  # uncomment the embed_templates/1 call below
  # and add pages to the error directory:
  #
  #   * lib/blog_web/controllers/error_html/404.html.heex
  #   * lib/blog_web/controllers/error_html/500.html.heex
  #
  # embed_templates "error_html/*"

  # The default is to render a plain text page based on
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def render(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/blog_web/controllers/page_controller.ex
defmodule BlogWeb.PageController do
  use BlogWeb, :controller

  #def home(conn, _params) do
    # The home page is often custom made,
    # so skip the default app layout.
   # render(conn, :home, layout: false)
  #end
  def about(conn, _params) do
    render(conn, "about.html")
  end

  def home(conn, _param) do
    render(conn, "home.html")
  end

end

lib/blog_web/controllers/page_html.ex
defmodule BlogWeb.PageHTML do
  use BlogWeb, :html

  # Certifique-se de que o diretório está configurado corretamente para os templates .heex (se você tiver algum).
  embed_templates "page_html/*"

  def about(assigns) do
    ~H"""
    <div class="about">
      <h1>Sobre Mim</h1>
      <p>Opa</p>
    </div>
    """
  end
end

lib/blog_web/controllers/post_controller.ex
defmodule BlogWeb.PostController do
  use BlogWeb, :controller

  alias Blog.Content
  alias Blog.Content.Post

  def index(conn, _params) do
    posts = Content.list_posts() |> Enum.sort_by(& &1.inserteed_at, :desc)
    render(conn, :index, posts: posts)
  end

  def new(conn, _params) do
    changeset = Content.change_post(%Post{})
    render(conn, :new, changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    case Content.create_post(post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: ~p"/posts/#{post}")

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, :new, changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    post = Content.get_post!(id)
    render(conn, :show, post: post)
  end

  def edit(conn, %{"id" => id}) do
    post = Content.get_post!(id)
    changeset = Content.change_post(post)
    render(conn, :edit, post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Content.get_post!(id)

    case Content.update_post(post, post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: ~p"/posts/#{post}")

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, :edit, post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Content.get_post!(id)
    {:ok, _post} = Content.delete_post(post)

    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: ~p"/posts")
  end
end

lib/blog_web/controllers/post_html.ex
defmodule BlogWeb.PostHTML do
  use BlogWeb, :html

  embed_templates "post_html/*"

  @doc """
  Renders a post form.
  """
  attr :changeset, Ecto.Changeset, required: true
  attr :action, :string, required: true

  def post_form(assigns)
end

lib/blog_web/components/layouts/app.html.heex
<header class="px-4 sm:px-6 lg:px-8">
  <div class="flex items-center justify-between border-b border-zinc-100 py-3 text-sm">
    <div class="flex items-center gap-4">
      <a href="/">
        <img src={~p"/images/logo.svg"} width="36" />
      </a>
      <p class="bg-brand/5 text-brand rounded-full px-2 font-medium leading-6">
        v<%= Application.spec(:phoenix, :vsn) %>
      </p>
    </div>
    <div class="flex items-center gap-4 font-semibold leading-6 text-zinc-900">
      <a href="https://twitter.com/elixirphoenix" class="hover:text-zinc-700">
        @elixirphoenix
      </a>
      <a href="https://github.com/phoenixframework/phoenix" class="hover:text-zinc-700">
        GitHub
      </a>
      <a
        href="https://hexdocs.pm/phoenix/overview.html"
        class="rounded-lg bg-zinc-100 px-2 py-1 hover:bg-zinc-200/80"
      >
        Get Started <span aria-hidden="true">&rarr;</span>
      </a>
    </div>
  </div>
</header>
<main class="px-4 py-20 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-2xl">
    <.flash_group flash={@flash} />
    <%= @inner_content %>
  </div>
</main>

lib/blog_web/components/layouts/root.html.heex
<!DOCTYPE html>
<html lang="en" class="[scrollbar-gutter:stable]">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content={get_csrf_token()} />
    <.live_title suffix=" · Phoenix Framework">
      <%= assigns[:page_title] || "Blog" %>
    </.live_title>
    <link phx-track-static rel="stylesheet" href={~p"/assets/app.css"} />
    <script defer phx-track-static type="text/javascript" src={~p"/assets/app.js"}>
    </script>
  </head>
  <body class="bg-white">
    <%= @inner_content %>
  </body>
</html>

lib/blog_web/controllers/post_html/edit.html.heex
<.header>
  Edit Post <%= @post.id %>
  <:subtitle>Use this form to manage post records in your database.</:subtitle>
</.header>

<.post_form changeset={@changeset} action={~p"/posts/#{@post}"} />

<.back navigate={~p"/posts"}>Back to posts</.back>

lib/blog_web/controllers/post_html/index.html.heex
<.header>
  Listing Posts
  <:actions>
    <.link href={~p"/posts/new"}>
      <.button>New Post</.button>
    </.link>
  </:actions>
</.header>

<.table id="posts" rows={@posts} row_click={&JS.navigate(~p"/posts/#{&1}")}>
  <:col :let={post} label="Title"><%= post.title %></:col>
  <:col :let={post} label="Body"><%= post.body %></:col>
  <:action :let={post}>
    <div class="sr-only">
      <.link navigate={~p"/posts/#{post}"}>Show</.link>
    </div>
    <.link navigate={~p"/posts/#{post}/edit"}>Edit</.link>
  </:action>
  <:action :let={post}>
    <.link href={~p"/posts/#{post}"} method="delete" data-confirm="Are you sure?">
      Delete
    </.link>
  </:action>
</.table>

lib/blog_web/controllers/post_html/new.html.heex
<.header>
  New Post
  <:subtitle>Use this form to manage post records in your database.</:subtitle>
</.header>

<.post_form changeset={@changeset} action={~p"/posts"} />

<.back navigate={~p"/posts"}>Back to posts</.back>

lib/blog_web/controllers/post_html/post_form.html.heex
<.simple_form :let={f} for={@changeset} action={@action}>
  <.error :if={@changeset.action}>
    Oops, something went wrong! Please check the errors below.
  </.error>
  <.input field={f[:title]} type="text" label="Title" />
  <.input field={f[:body]} type="text" label="Body" />
  <:actions>
    <.button>Save Post</.button>
  </:actions>
</.simple_form>

lib/blog_web/controllers/post_html/show.html.heex
<.header>
  Post <%= @post.id %>
  <:subtitle>This is a post record from your database.</:subtitle>
  <:actions>
    <.link href={~p"/posts/#{@post}/edit"}>
      <.button>Edit post</.button>
    </.link>
  </:actions>
</.header>

<.list>
  <:item title="Title"><%= @post.title %></:item>
  <:item title="Body"><%= @post.body %></:item>
</.list>

<.back navigate={~p"/posts"}>Back to posts</.back>

lib/blog_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <header>
        <nav>
            <ul>
                <li><a href="<%= Routes.page_path(@conn, :home) %>">Home</a></li>
                <li><a href="<%= Routes.page_path(@conn, :about) %>">Sobre Mim</a></li>
                <li><a href="<%= Routes.page_path(@conn, :index) %>">Posts</a></li>
            </ul>
        </nav>

    </header>
    <main role="main">
        <%= @inner_content %> 
    </main>
</body>
</html>

lib/blog_web/templates/page/about.html.heex
<div class="about">
    <h1>Sobre mim</h1>
    <p>a vontade</p>
</div>

lib/blog_web/templates/page/home.html.heex
<div class="home">
    <h1>bem vindo</h1>
    <p>:Posts</p>
    <div>a</div>
</div>

lib/blog_web/templates/page/index.html.heex
<div class="posts">
    <h1>Posts</h1>
    <ul>
        <%= for post <- @posts do %>
        <li>
            <h2> <a href="<%= Routes.post_path(@conn, :show, post) %>"><%= post.title %></a></h2>
            <p> <%= post.body |> String.slice(0..100) %>...</p>
        </li>
        <% end %>
        <div>a</div>
    </ul>
</div>

lib/blog_web/templates/post/index.html.heex
<div class="posts">
    <h1>Posts</h1>
    <ul>
      <%= for post <- @posts do %>
        <li>
          <h2><a href="<%= Routes.post_path(@conn, :show, post) %>"><%= post.title %></a></h2>
          <p><%= post.body |> String.slice(0..100) %>...</p>
        </li>
      <% end %>
    </ul>
  </div>
  

lib/blog_web/templates/posts/show.html.heex
<div class="posts">
    <h1><%= @post.title %></h1>
    <p><%= @post.body %></p>
    <a href="<%= Routes.post_path(@conn, :index) %>">Voltar para os posts</a>
</div>